name: test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: |
          NDK_VERSION=20.0.5594570
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${NDK_VERSION}" --sdk_root=${ANDROID_SDK_ROOT}
          export ANDROID_NDK_ROOT=${ANDROID_HOME}/ndk/${NDK_VERSION}
      
      - name: Setup Debug Session
        uses: mxschmitt/action-tmate@v3
       
